### PR TITLE
Remove extra isset() calls

### PR DESCRIPTION
**Pull request by sneurlax**
I had planned in https://github.com/sneurlax/monerophp/issues/6 to expand these isset() calls with type and validity checking, but php already checks that methods are called with all required parameters and monero-wallet-rpc already checks for validity, so these aren't needed.

If others think that full validation would be good, discuss, but this pull request removes them all.

### CODE REVIEW

**Comment by sneurlax** [comment]
OK, getting `Notice: Undefined variable: do_not_relay in /home/r/github/monerophp/src/walletRPC.php on line 486` in example.php for transfer, so adding just some back to transfer and sweep methods

**Comment by serhack** [comment]
I agree for removing those. @cryptochangements34 what do you think?

**Comment by sneurlax** [comment]
I set default value for `do_not_relay` instead of adding an isset() back and tested that adding default/empty parameters works just fine, so condensed the transfer and sweep methods a bit more.

I will say that you'll see some array_key_exists still, and I think those are needed when passing in parameters as objects.  See transfer():

`transfer($amount, $address = '', $payment_id = '', $mixin = 6, $index = 0, $priority = 2, $unlock_time = 0, $do_not_relay = false)`

If you wanted to send 2 moneroj to an address and wanted it to not be relayed but didn't care about any of the other parameters, you could just do `transfer(['amount' => 2, 'address' => '9sZABNdyWspcpsCPma1eUD5yM3efTHfsiCx3qB8RDYH9UFST4aj34s5Ygz69zxh8vEBCCqgxEZxBAEC4pyGkN4JEPmUWrxn', 'do_not_relay' => true])` ... so I left those array_key_exists in the case that the user feeds an object in

**Comment by cryptochangements34** [comment]
I'm cool with it. As I understand it #49 includes these commits so we can just merge that

**Comment by sneurlax** [comment]
Superseded by #49

**Pull request closed without merging**
