### PR TITLE
fix method name in rpc

### PR DESCRIPTION
**Pull request by mzk**
https://getmonero.org/resources/developer-guides/wallet-rpc.html !

### CODE REVIEW

**Comment by mzk** [comment]
I'm using this library for sumokoin (fork monero). 
And there don't have aliases.

look https://github.com/sumoprojects/sumokoin/blob/master/src/wallet/wallet_rpc_server.h 

So I agree with your argument, but I prefer better compatibility (depends on documentation https://getmonero.org/resources/developer-guides/wallet-rpc.html, not on the code). 

The Code can be changed.

**Comment by mzk** [comment]
The library `monero-integrations/monerophp` can offer an aliases (`$client->getbalance(), $client->get_balance()`, $client->getMyBalance()`.

But always call the default and documented method `return $this->_run('getbalance', $params);`. Not aliased method name.  imho.

**Comment by serhack** [comment]
> I'm using this library for sumokoin (fork monero).

I'm sorry. We don't support forks of Monero.

> But always call the default and documented method return $this->_run('getbalance', $params);. 

It's wrong, see https://github.com/monero-integrations/monerophp/blob/master/src/walletRPC.php#L128

**Comment by mzk** [comment]
> I'm sorry. We don't support forks of Monero.

Ok
> It's wrong, see https://github.com/monero-integrations/monerophp/blob/master/src/walletRPC.php#L128

nope: https://getmonero.org/resources/developer-guides/wallet-rpc.html#getbalance => getbalance not get_balance.

**Comment by sneurlax** [comment]
@mzk, that documentation is out of date.  It even says so at the top.  Our documentation is actually the most up to date, see [/docs](https://github.com/monero-integrations/monerophp/tree/master/docs)

What aliases would be required in order to support forks more easily?

**Pull request closed without merging**
